# 项目名称
spring.application.name=yubico_otp
# 运行端口
server.port=8080
# 日志级别
logging.level.com.m4passion= INFO
# 日志文件配置
logging.file.name=./yubico_otp.log

# 根据 h2 部署信息修改数据库配置
spring.datasource.url=jdbc:h2:file:./yubico_otp;MODE=MySQL;DATABASE_TO_UPPER=FALSE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
spring.sql.init.platform=h2
spring.sql.init.schema-locations=classpath:schema-h2.sql

# 公开标识与序列号的关联性的校验，若开启则只允许使用默认公开标识进行注册和使用
verify.check-serial= false

spring.jackson.default-property-inclusion= non_null