# 项目名称
spring.application.name=yubico_otp
# 运行端口
server.port=8080
# 日志级别
logging.level.com.m4passion= INFO
# 日志文件配置
logging.file.name=./yubico_otp.log

# 根据mysql部署信息修改数据库配置
spring.datasource.url=jdbc:mysql://localhost:3306/yubico_otp?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=yubico_otp
spring.datasource.password=yubico_otp

# 公开标识与序列号的关联性的校验，若开启则只允许使用默认公开标识进行注册和使用
verify.check-serial= false

spring.jackson.default-property-inclusion= non_null